before_script:
  - pwd
  - whoami
  - which python
  - which pip
  - conda install numpy scipy llvmlite numba scikit-learn
  - pip install -r requirements.txt

unittest:
  script:
    - python -m unittest tvb_hpc.tests

style:
  script:
    - flake8

example_hackathon:
  script:
    - python examples/hackathon.py

# vim: sw=2 sts=2 et ai
