before_script:
  - pwd
  - whoami
  - conda env list
  - source activate tvb-hpc

unittest:
  script:
    - python -m unittest tvb_hpc.tests

examples:
  script:
    - python -m unittest tvb_hpc.examples

# vim: sw=2 sts=2 et ai
