stages:
  - info
  - build
  - lint
  - test
  - package

info:
  stage: info
  script:
    - pwd
    - whoami
    - which python
    - which pip

build_env:
  stage: build
  script:
    - conda install numpy scipy llvmlite numba scikit-learn
    - pip install -r requirements.txt
    - python setup.py install

flake8:
  stage: lint
  script:
    - flake8

mypy:
  stage: lint
  script:
    - mypy tvb_hpc

unittest:
  stage: test
  script:
    - python -m unittest tvb_hpc.tests

example_hackathon:
  stage: test
  script:
    - python examples/hackathon.py

wheel:
  stage: package
  script:
    - python setup.py bdist_wheel

# vim: sw=2 sts=2 et ai
