# thx http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
sudo: required
dist: precise
language: cpp
python:
    - 3.6
    - 2.7
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CXX=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: CXX=clang++-3.7
before_install:
    - sudo apt-get update -qq
script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=$CXX ..
    - make
    - make test

notifications:
    slack:
        secure: Bh4k0UAj//wjtqvZXIm3ft2Hafd8BmVfpoGJJKfM2wIbEM7Rkw4HbVBhwbDqJTU/LTRWHj29Mcd9lM/DK1k/o4apqatzdtSiuP/fxJAZQT4veHSjyFBv6S+dySok0GbioAAswu0xkPace2z74kL5paW6xCEtg58Y7YOMsdoYpCat9c5OtK1IWT+ER0tfqItISZKGL9px2aoZG3KpSoehpKXREriygNr5iUXrtxTHJMMVt3qOrLqkc1hukp4XofIf28s3ekURgZP0IOMEX1UFKi6cfolfzPMqvyA1aV3ZTzvEbEvfQbEIpTnD3/nlW7IYFGo5z7bBwnh3sO+azktlvDjeW7nrW1KHnikH+5g+h/VLgECeb0LCEzHlwUL+a4Q5sOaDsXsmHEjWWOr/30GicqBYtTBj4YsBp3EkjPJEYg+rkebpzwWBreWpHNFsL8pgJKRuVG3AfPqgUwuDLnxC0UAAgyGGb4lUd0GEfeeL1S8BGA1n0rgHseZAcrooboMlNDJvMwlloW8rsaVGLKSE3HBNKBKi77+h1YBmCqCiZTvulz0tDDHiIJCINndx7Fdc7AXwIzKEPckckVXN5T17uAwa3WCsBWgNADnoJHoZ5O9uJ1UoZQWq70haQQjdkXpA+IH7CrqDnw5TGy+Sfd/lQ4J9VcLJbMa8rz1RxdCs/No=
