language: python
python:
    - "3.6"
env:
  - CC=clang CXX=clang++ CXXFLAGS="-Wall -Wextra" TVB_LOG=DEBUG PREFIX=./test-env
  - CC=gcc CXX=g++ CXXFLAGS="-Wall -Wextra" TVB_LOG=DEBUG SANFLAGS="" PREFIX=./test-env
install:
    - env/make-env.sh
script:
    - "$PREFIX/bin/python3 -m unittest tvb_hpc.tests"

#   - "$PREFIX/bin/flake8 tvb_hpc"

# - $PREFIX/bin/mypy --ignore-missing-imports tvb_hpc
