language: python
python:
    - "3.6"
env:
  - CC=clang CXX=clang++ CXXFLAGS="-Wall -Wextra" TVB_LOG=DEBUG SANFLAGS=""
  - CC=gcc CXX=g++ CXXFLAGS="-Wall -Wextra" TVB_LOG=DEBUG SANFLAGS=""
install:
    - "pip install -r requirements-dev.txt"
script:
    - "python3 -m unittest tvb_hpc.tests"
    - "flake8 tvb_hpc"
