#!/bin/bash

rm error.er 
rm output.out
sed -e 's/bencharg/$1/;s/mdlrun/$2/' benchAll.sh > sed.txt
sed -e 's/bencharg/$1/' -e 's/mdlrun/$2/' benchAll.sh | bsub
#sleep 2

while [ ! -f ./error.er ] ;
do
  sleep 0.2 
done

if [ $1 == "regular" ]; 
then
  tail -f ./output.out | grep -i -E "INFO|WARNING|ERROR"
  tail -f ./error.er
else
  tail -f ./error.er
fi
